version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: '7.3.x-webserver'
    restart: 'always'
    environment:
      - PUID= 1000
      - PGID= 1000
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - 9000:9000
    links:
      - postgresql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  postgresql:
    image: postgres:latest
    container_name: 'postgres'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/mysql
      - ${POSTGRES_LOG_DIR}:/var/log/mysql
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${PG_DB}